=== rnhc1000/XML/Demo2/cd_catalog.dtd
<!ELEMENT CATALOG (CD*)>
  <!ELEMENT CD (TITLE,ARTIST,COUNTRY,COMPANY,PRICE?,COST,YEAR,INVENTORY?,BIN?)>
  <!ELEMENT TITLE (#PCDATA)>
  <!ELEMENT ARTIST (#PCDATA)>
  <!ELEMENT COUNTRY (#PCDATA)>
  <!ELEMENT COMPANY (#PCDATA)>
  <!ELEMENT PRICE (#PCDATA)>  
  <!ELEMENT COST (#PCDATA)>
  <!ELEMENT YEAR (#PCDATA)>
   <!ELEMENT INVENTORY (#PCDATA)>
    <!ELEMENT BIN (#PCDATA)>

=== rnhc1000/XML/Demo2/cd_catalog.xml
<?xml version="1.0"?>
<!DOCTYPE CATALOG SYSTEM "cd_catalog.dtd">
<CATALOG>
  <CD>
	  <TITLE>The Dark Side of the Moon</TITLE>
	  <ARTIST>Pink Floyd</ARTIST>
	  <COUNTRY>USA</COUNTRY>
	  <COMPANY>Capital Records</COMPANY>
	  <PRICE>12.99</PRICE>
	  <COST>5.99</COST>
	  <YEAR>1973</YEAR>
	  <INVENTORY>3</INVENTORY>
  </CD>
  <CD>
	  <TITLE>Houses of the Holy</TITLE>
	  <ARTIST>Led Zeppelin</ARTIST>
	  <COUNTRY>USA</COUNTRY>
	  <COMPANY>Atlantic Records</COMPANY>
	  <COST>5.99</COST>
	  <YEAR>1973</YEAR>
	  <BIN>1A3C</BIN>
  </CD>
  <CD>
	  <TITLE>Beggars Banquet</TITLE>
	  <ARTIST>Rolling Stones</ARTIST>
	  <COUNTRY>USA</COUNTRY>
	  <COMPANY>Decca Records</COMPANY>
	  <PRICE>11.99</PRICE>
	  <COST>5.99</COST>
	  <YEAR>1968</YEAR>
  </CD>
 </CATALOG>
