=== rnhc1000/XML/Demo5/cd_catalog.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="CATALOG">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="CD" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="TITLE"/>
              <xs:element type="xs:string" name="ARTIST"/>
              <xs:element type="xs:string" name="COUNTRY"/>
              <xs:element type="xs:string" name="COMPANY"/>
              <xs:element type="xs:float" name="PRICE"/>
              <xs:element type="xs:float" name="COST" minOccurs="0"/>
              <xs:element type="xs:short" name="YEAR"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rnhc1000/XML/Demo5/cd_catalog.xml
<?xml version="1.0" encoding="UTF-8" ?>
<CATALOG xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="cd_catalog.xsd">
  <CD>
	  <TITLE>The Dark Side of the Moon</TITLE>
	  <ARTIST>Pink Floyd</ARTIST>
	  <COUNTRY>USA</COUNTRY>
	  <COMPANY>Capital Records</COMPANY>
	  <PRICE>12.99</PRICE>
	  <COST>5.99</COST>
	  <YEAR>1973</YEAR>
  </CD>
  <CD>
	  <TITLE>Houses of the Holy</TITLE>
	  <ARTIST>Led Zeppelin</ARTIST>
	  <COUNTRY>USA</COUNTRY>
	  <COMPANY>Atlantic Records</COMPANY>
	  <PRICE>13.99</PRICE>
	  <COST>5.99</COST>
	  <YEAR>1973</YEAR>
  </CD>
  <CD>
	  <TITLE>Beggars Banquet</TITLE>
	  <ARTIST>Rolling Stones</ARTIST>
	  <COUNTRY>USA</COUNTRY>
	  <COMPANY>Decca Records</COMPANY>
	  <PRICE>11.99</PRICE>
	  <COST>5.99</COST>
	  <YEAR>1968</YEAR>
  </CD>
  <CD>
	  <TITLE>Still got the blues</TITLE>
	  <ARTIST>Gary Moore</ARTIST>
	  <COUNTRY>UK</COUNTRY>
	  <COMPANY>Virgin records</COMPANY>
	  <PRICE>10.20</PRICE>
	  <YEAR>1990</YEAR>
  </CD>
</CATALOG>
