=== rnhc1000/XML/Demo4/cd_catalog.dtd
<!ELEMENT CATALOG (CD*,VINYL*,COPYRIGHT)>
<!--CD DECLARATIONS-->
<!ELEMENT CD (cd:TITLE,cd:ARTIST,cd:COUNTRY,cd:COMPANY,cd:PRICE?,cd:COST,cd:YEAR,cd:INVENTORY?)>
<!ATTLIST CD genre CDATA #IMPLIED 
                           xmlns:cd CDATA #FIXED "http://rockclassics.com/dtds/"> 
<!ELEMENT cd:TITLE (#PCDATA)>
<!ELEMENT cd:ARTIST (#PCDATA)>
<!ELEMENT cd:COUNTRY (#PCDATA)>
<!ELEMENT cd:COMPANY (#PCDATA)>
<!ELEMENT cd:PRICE (#PCDATA)>  
<!ELEMENT cd:COST (#PCDATA)>
<!ELEMENT cd:YEAR (#PCDATA)>
<!ELEMENT cd:INVENTORY (#PCDATA)>
<!ELEMENT cd:BIN (#PCDATA)>
<!ELEMENT VINYL (vy:TITLE,vy:ARTIST,vy:COUNTRY,vy:COMPANY,vy:PRICE?,vy:COST,vy:YEAR,vy:INVENTORY?)>
<!--VINYL DECLARATIONS-->
<!ATTLIST VINYL genre CDATA #IMPLIED 
                           xmlns:vy CDATA #FIXED "http://rockclassics.com/dtds/"> 
<!ELEMENT vy:TITLE (#PCDATA)>
<!ELEMENT vy:ARTIST (#PCDATA)>
<!ELEMENT vy:COUNTRY (#PCDATA)>
<!ELEMENT vy:COMPANY (#PCDATA)>
<!ELEMENT vy:PRICE (#PCDATA)>  
<!ELEMENT vy:COST (#PCDATA)>
<!ELEMENT vy:YEAR (#PCDATA)>
<!ELEMENT vy:INVENTORY (#PCDATA)>
<!ELEMENT vy:BIN (#PCDATA)>
<!ENTITY cn "Rock Classics, Ltd.">
<!ENTITY c "Copyright &cn; All Rights Reserved.">
<!ELEMENT COPYRIGHT (#PCDATA)>

=== rnhc1000/XML/Demo4/cd_catalog.xml
<?xml version="1.0"?>
<!DOCTYPE CATALOG SYSTEM "cd_catalog.dtd">
<CATALOG>
  <CD genre="Rock">
	  <cd:TITLE>The Dark Side of the Moon</cd:TITLE>
	  <cd:ARTIST>Pink Floyd</cd:ARTIST>
	  <cd:COUNTRY>USA</cd:COUNTRY>
	  <cd:COMPANY>Capital Records</cd:COMPANY>
	  <cd:PRICE>12.99</cd:PRICE>
	  <cd:COST>5.99</cd:COST>
	  <cd:YEAR>1973</cd:YEAR>
	  <cd:INVENTORY>3</cd:INVENTORY>
  </CD>
  <CD genre="Rock">
	  <cd:TITLE>Houses of the Holy</cd:TITLE>
	  <cd:ARTIST>Led Zeppelin</cd:ARTIST>
	  <cd:COUNTRY>USA</cd:COUNTRY>
	  <cd:COMPANY>Atlantic Records</cd:COMPANY>
	  <cd:COST>5.99</cd:COST>
	  <cd:YEAR>1973</cd:YEAR>
	  <cd:INVENTORY>2</cd:INVENTORY>
  </CD>
  <CD genre="Rock">
	  <cd:TITLE>Beggars Banquet</cd:TITLE>
	  <cd:ARTIST>Rolling Stones</cd:ARTIST>
	  <cd:COUNTRY>USA</cd:COUNTRY>
	  <cd:COMPANY>Decca Records</cd:COMPANY>
	  <cd:PRICE>11.99</cd:PRICE>
	  <cd:COST>5.99</cd:COST>
	  <cd:YEAR>1968</cd:YEAR>
 	  <cd:INVENTORY>1</cd:INVENTORY>
 </CD>
 <VINYL genre="Rock">
	  <vy:TITLE>Who's Next</vy:TITLE>
	  <vy:ARTIST>The Who</vy:ARTIST>
	  <vy:COUNTRY>USA</vy:COUNTRY>
	  <vy:COMPANY>Decca Records</vy:COMPANY>
	  <vy:PRICE>19.99</vy:PRICE>
	  <vy:COST>9.99</vy:COST>
	  <vy:YEAR>1971</vy:YEAR>
 	  <vy:INVENTORY>1</vy:INVENTORY>
 </VINYL>
 <COPYRIGHT>&c;</COPYRIGHT>
 </CATALOG>
