=== rnhc1000/XML/Demo3/cd_catalog.dtd
<!ELEMENT CATALOG (CD*,COPYRIGHT)>
<!ELEMENT CD (TITLE,ARTIST,COUNTRY,COMPANY,PRICE?,COST,YEAR,INVENTORY?)>
<!ATTLIST CD genre CDATA #IMPLIED> 
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT ARTIST (#PCDATA)>
<!ELEMENT COUNTRY (#PCDATA)>
<!ELEMENT COMPANY (#PCDATA)>
<!ELEMENT PRICE (#PCDATA)>  
<!ELEMENT COST (#PCDATA)>
<!ELEMENT YEAR (#PCDATA)>
<!ELEMENT INVENTORY (#PCDATA)>
<!ELEMENT BIN (#PCDATA)>
<!ENTITY cn "Rock Classics, Ltd.">
<!ENTITY c "Copyright &cn; All Rights Reserved.">
<!ELEMENT COPYRIGHT (#PCDATA)>

=== rnhc1000/XML/Demo3/cd_catalog.xml
<?xml version="1.0"?>
<!DOCTYPE CATALOG SYSTEM "cd_catalog.dtd">
<CATALOG>
  <CD genre="Rock">
	  <TITLE>The Dark Side of the Moon</TITLE>
	  <ARTIST>Pink Floyd</ARTIST>
	  <COUNTRY>USA</COUNTRY>
	  <COMPANY>Capital Records</COMPANY>
	  <PRICE>12.99</PRICE>
	  <COST>5.99</COST>
	  <YEAR>1973</YEAR>
	  <INVENTORY>3</INVENTORY>
  </CD>
  <CD genre="Rock">
	  <TITLE>Houses of the Holy</TITLE>
	  <ARTIST>Led Zeppelin</ARTIST>
	  <COUNTRY>USA</COUNTRY>
	  <COMPANY>Atlantic Records</COMPANY>
	  <COST>5.99</COST>
	  <YEAR>1973</YEAR>
	  <INVENTORY>2</INVENTORY>
  </CD>
  <CD genre="Rock">
	  <TITLE>Beggars Banquet</TITLE>
	  <ARTIST>Rolling Stones</ARTIST>
	  <COUNTRY>USA</COUNTRY>
	  <COMPANY>Decca Records</COMPANY>
	  <PRICE>11.99</PRICE>
	  <COST>5.99</COST>
	  <YEAR>1968</YEAR>
 	  <INVENTORY>1</INVENTORY>
 </CD>
 <COPYRIGHT>&c;</COPYRIGHT>
 </CATALOG>
